services:
  consumerservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080"

  producerservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080"

